info:
  app.name: producer-system
  app.version: V1.0.0
app:
  id: SampleApp
#apollo:
#  meta: http://192.168.1.73:8280
spring:
  application:
    name: producer-system
  boot:
    admin:
      client:
        url: http://localhost:8090
        username: "jarvis"
        password: "weiyu@2018"
        instance:
          prefer-ip: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.40.217:3306/platformdb?characterEncoding=utf8&verifyServerCertificate=false&useSSL=true
    username: root
    password: 123456
    # 下面为连接池的补充设置，应用到上面所有数据源中
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    logSlowSql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8081
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:1111/eureka/
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: ALWAYS
#mybatis
mybatis:
  type-aliases-package: com.apiserver.model.system.entity
  mapper-locations: classpath:mapper/*.xml
#第三方支持
qiniu:
  accessKey: T30fx_iEO0cNI-gGdaq_gI8XEnMMRbxVUs1m-X_y
  secretKey: 6a6GZYmolO79nvpfOLXSq8TDosZCyHW137NfVHgy
  bucket: labcpic

alphaMessages:
  email:
    title:
      register.cn: AlphaBiz 安全认证
      register.en: AlphaBiz safety certificate
    body:
      register.cn: 您的验证码是:<font color="#fff"> {0} </font>.<br>出于安全考虑, 请勿将验证码透露给他人, 验证码有效期15分钟。<br>
      register.en: Your verification code is:<font color="#fff">{0}</font>.<br>For security reasons, please do not tell others ,that it is valid for 15 minutes.<br>

# 打印sql
logging:
  level:
    com:
      apiserver:
        producer:
          system:
            mapper: debug
